/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clicker;

/**
 *
 * @author patatuffolo
 */
public class Cookie extends javax.swing.JFrame {

    /**
     * Creates new form Cookie
     */
    public Cookie() {
        initComponents();
        btn_click.setLocation(HEIGHT/2, WIDTH/2);
        lbl_error.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_click = new javax.swing.JButton();
        btn_up1 = new javax.swing.JButton();
        lbl_cost1 = new javax.swing.JLabel();
        lbl_co = new javax.swing.JLabel();
        lbl_up = new javax.swing.JLabel();
        lbl_error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 102, 255));

        btn_click.setBackground(new java.awt.Color(102, 102, 255));
        btn_click.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        btn_click.setText("COOKIE");
        btn_click.setBorder(null);
        btn_click.setBorderPainted(false);
        btn_click.setFocusPainted(false);
        btn_click.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clickActionPerformed(evt);
            }
        });

        btn_up1.setFont(new java.awt.Font("Copperplate", 0, 18)); // NOI18N
        btn_up1.setText("Value Up");
        btn_up1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_up1.setBorderPainted(false);
        btn_up1.setContentAreaFilled(false);
        btn_up1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_up1ActionPerformed(evt);
            }
        });

        lbl_cost1.setFont(new java.awt.Font("Copperplate", 0, 13)); // NOI18N
        lbl_cost1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cost1.setText("cost: 1");

        lbl_co.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        lbl_co.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_co.setBorder(javax.swing.BorderFactory.createTitledBorder("Cookies"));

        lbl_up.setFont(new java.awt.Font("Copperplate", 0, 13)); // NOI18N
        lbl_up.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_up.setText("Lvl. 1");

        lbl_error.setBackground(new java.awt.Color(255, 255, 255));
        lbl_error.setFont(new java.awt.Font("PT Mono", 0, 13)); // NOI18N
        lbl_error.setForeground(new java.awt.Color(255, 0, 0));
        lbl_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_error.setText("Non hai abbastanza biscotti D:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_co, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addComponent(btn_up1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_click, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_cost1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_up, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbl_co, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addGap(89, 89, 89)
                .addComponent(btn_click, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(lbl_error, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cost1)
                    .addComponent(lbl_up))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_up1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int cookies = 0;
    
    private void btn_clickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clickActionPerformed
        cookies+=1*vup;
        lbl_co.setText(String.valueOf(cookies));
        lbl_error.setVisible(false);
    }//GEN-LAST:event_btn_clickActionPerformed
    int vup = 1, vb = 0, cup = 1, cb = 1;
    private void btn_up1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_up1ActionPerformed
        if (cookies >= cup) {
            lbl_error.setVisible(false);
            cookies -= cup;
            lbl_co.setText(String.valueOf(cookies));
            vup += 1;
            cup *= 2;
            Math.round(vup); Math.round(cup);
            lbl_cost1.setText("Costo: " + cup);
            lbl_up.setText("Lvl. " + vup);
            System.out.println("cook: " + cookies + ", costo up:" + cup + ", valore up:" + vup);
        } else {
            lbl_error.setVisible(true);
        }
    }//GEN-LAST:event_btn_up1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cookie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cookie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cookie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cookie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cookie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_click;
    private javax.swing.JButton btn_up1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_co;
    private javax.swing.JLabel lbl_cost1;
    private javax.swing.JLabel lbl_error;
    private javax.swing.JLabel lbl_up;
    // End of variables declaration//GEN-END:variables
}
